name: "File existence check"
on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  file_existence:
    runs-on: ubuntu-latest
    steps:
      - name: Repo lowecase
        run: |
          echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
          
      - name: Checkout repo
        uses: actions/checkout@v1


      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "Dockerfile"

      - name: File exists
        if: steps.check_files.outputs.files_exists == 'true'
        uses: docker/build-push-action@v2
        with:
          username: Aleks-dotcom
          password: ${{ secrets.REGISTRY_TOKEN }}
          registry: docker.pkg.github.com
          repository: ${{ env.REPO }}/image
          tag_with_ref: true
