name: "File existence check"
on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  file_existence:
    runs-on: ubuntu-latest
    steps:
      - name: Repo lowecase
        run: |
          echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
          
      - name: Repo lowecase2
        run: |
          echo "REPO_END=$(echo "${{ github.event.repository.name }}" | tr '[:upper:]' '[:lower:]')" >>${GITHUB_ENV}
          
      - name: Checkout repo
        uses: actions/checkout@v1


      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "Dockerfile"

      - name: File exists
        if: steps.check_files.outputs.files_exists == 'true'
        uses: docker/build-push-action@v1
        with:
          username: dsecid
          password: ${{ secrets.REGISTRY_TOKEN }}
          registry: ghcr.io
          repository: ${{ env.REPO }}
          tag_with_ref: true
