name: "File existence check"
on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  file_existence:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v1

      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "Dockerfile"

      - name: File exists
        if: steps.check_files.outputs.files_exists == 'true'
        steps:
          - name: Push to GitHub Packages
            uses: docker/build-push-action@v1
            with:
              username: Aleks-dotcom
              password: ${{ secrets.REGISTRY_TOKEN }}
              registry: docker.pkg.github.com
              repository: dragonsecsi/${{ github.repository }}
              tag_with_ref: true
